#STATUS_LOG = "c:/temp/one_status.log"
#CONFIG_FILE = "c:/temp/one_config.json"    
#IP_FILE = "c:/temp/one_last_ip.txt"
STATUS_LOG = "/data/status.log"
CONFIG_FILE = "/data/config.json"
IP_FILE = "/data/last_ip.txt"
